---
language: python
python: "3.8"

sudo: required
dist: bionic

addons:
  apt:
    packages:
      - python-pip
      - libssl-dev

install:
  - pip install molecule docker

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
