---
- name: Install build dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_flattened:
    - "{{ pyenv_debian_build_dependencies }}"
    - "{{ pyenv_debian_additional_build_dependencies }}"
  become: true
  when: pyenv_is_dependencies_installed
