---
# tasks file for pyenv
- name: ghq root
  shell: "{{ghq_executable}} root"
  register: ghq_root
  changed_when: false
- name: Clone pyenv repository
  ghq:
    executable: "{{ghq_executable}}"
    name: pyenv/pyenv
    update: yes
- name: Check $PYENV_ROOT
  stat:
    path: "{{ pyenv_root }}"
  register: st
- name: Back up $PYENV_ROOT
  shell: "mv {{ pyenv_root }} {{ pyenv_root }}.{{ansible_date_time.date}}-{{ansible_date_time.hour}}-{{ansible_date_time.minute}}-{{ansible_date_time.second}}"
  when: st.stat.exists and not st.stat.islnk
- name: Make symbolic links
  file:
    src: "{{ghq_root.stdout}}/github.com/pyenv/pyenv"
    dest: "{{ pyenv_root }}"
    state: link
- name: Notice
  debug:
    msg: "Install pyenv install dependencies."
- name: Notice
  debug:
    msg: "export PYENV_ROOT=$HOME/.pyenv"
- name: Notice
  debug:
    msg: "export PATH=$PYENV_ROOT/bin:$PATH"
- name: Notice
  debug:
    msg: "eval \"$(pyenv init -)\""
