---
- name: Install build dependencies
  yum:
    name: "{{ query('flattened', ['{{ pyenv_redhat_build_dependencies }}', '{{ pyenv_redhat_additional_build_dependencies }}']) }}"
    update_cache: true
  become: true
  when: pyenv_is_dependencies_installed|bool
